name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_ID: ${{ vars.BUILD_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.7.0
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: linktodream/unpkg
        flavor: |
          latest=true
          prefix=
          suffix=
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
